name: blog
channels:
  - conda-forge
dependencies:
  - python=3
  - jupyter
  - jupyterlab
  - nbconvert
  - urllib3
  - matplotlib
  - plotly
  - bokeh
  - pip:
    - pelican>=3.6.0
    - Markdown==2.6.2
    - jsonschema==2.4.0
    - mistune==0.5.1
    - pylint
